---
title: "mm21.08 Cell2Location"
author: "Shoumit Dey"
date: '01/01/2023'
output: html_document
---

```{r setup, include=FALSE}
library(Seurat)
library(SeuratObject)
library(cowplot)
library(dplyr)
library(ggplot2)
library(stringr)
library(sqldf)
library(ggpubr)
library(reshape2)
library(igraph)
library(corrplot)
library(RColorBrewer)

output_integrated <- paste0(getwd(),"/")

dir.create(paste0(output_integrated, "spatial_outputs"))
save_path<-paste0(getwd(),"/spatial_outputs/")
```



```{r read_in_data}
only_mm2108_skin_merged <- readRDS(paste0(output_integrated, "only_mm2108_skin_merged.rds"))
```
##################################
-Loads cell2location learned cell abundances in spatial data
and adds it as metadata to spatial seurat object
-Main figure 8a 
##################################
```{r change_meta}
cell2location_abundances <- read.csv(paste0(output_integrated, "q05_cell_abundance_w_sf_barcoded.csv"))
rownames(cell2location_abundances)<-cell2location_abundances$spot_id
#Fine grained celltypes (SubCellTypeM) from the single cell data
#See integrated_downstream.Rmd
#  [1] "Mast"                "NK"                  "Naive"               "Prolif.T"            "Th1"                 "Th2"                 "gdT"                
#  [8] "Basal"               "DCs"                 "EndoI0"              "EndoI1"              "EndoI2"              "EndoI3"              "EndoI4"             
# [15] "EndoI5"              "EndoI6"              "FI"                  "FII"                 "FIII"                "FIV"                 "FV"                 
# [22] "FVI"                 "Inflam..mono"        "LECLV0"              "LECLV1"              "LECLV2"              "Langerhans.cells"    "Mo.derived.Macs"    
# [29] "Myofibroblasts"      "NK.like"             "Neutrophils"         "Prolif..Myeloid"     "RBCs"                "Reg.TAMs..Resident." "Schwann"            
# [36] "Sebocytes"           "tDP"   
cell_types<-colnames(cell2location_abundances)
cell_types<-cell_types[2:length(cell_types)]


df<-cell2location_abundances[,cell_types]

# calculate the maximum of each column
df_max <- apply(df, 2, max)
#df_max <- colMaxs(df) requires a package

# sort the dataframe based on the mean values
df_sorted <- df[, order(df_max, decreasing = T)]
df_melt <- melt(df_sorted)

pdf(paste0(save_path, "Figure8a.pdf"), height = 10, width=7)
  ggplot(data = df_melt, aes(x = value, y = variable, fill = variable)) + 
        geom_boxplot() + 
        coord_flip()  + 
        theme_classic() + 
        theme(legend.position="none", axis.text.x = element_text(angle = 90, hjust = 1)) +
        geom_vline(aes(xintercept = median(df_max)), col = "red", size = 0.3) +
        ylab(label = "") +
        xlab(label = "Cell2Location q05 abundances")
dev.off() 
#threshold abundances
subset_df_max <- subset(df_max, df_max>median(df_max))
cell2location_abundances_thresholded <- cell2location_abundances[, names(subset_df_max)]
#already stored in the rds. Only uncomment when running all over again
only_mm2108_skin_merged<-AddMetaData(only_mm2108_skin_merged, metadata = cell2location_abundances_thresholded)

thresh_cell_types <- colnames(cell2location_abundances_thresholded)

```
##################################
-PDF containing:
Main figure 8c & f
Suppl. figure 8b
Suppl. figure 9
##################################
```{r spatial_maps}

pdf(paste0(save_path, "spatial_figures_celltype_abundances.pdf"), height = 9, width=15)
  for(image_count in 1:length(only_mm2108_skin_merged@images)){
    image<-names(only_mm2108_skin_merged@images)[image_count]
    print(SpatialFeaturePlot(only_mm2108_skin_merged, features = head(thresh_cell_types,9), image.alpha = 0, pt.size.factor = 4, alpha = c(0.1,2), images =image, ncol = 3))
    print(SpatialFeaturePlot(only_mm2108_skin_merged, features = tail(thresh_cell_types,9), image.alpha = 0, pt.size.factor = 4, alpha = c(0.1,2), images = image, ncol = 3))
  }
dev.off()


```

##################################
-PDFs containing:
Main figure 8a & d
##################################

```{r corrplots per group}
#corrplots per group
only_mm2108_skin_merged<-SetIdent(only_mm2108_skin_merged, value = "group")
for(group in unique(only_mm2108_skin_merged$group)){
  obj<-subset(only_mm2108_skin_merged, idents=group)
  cell2location_abundances<-obj@meta.data[, thresh_cell_types]
  cell2location_abundances_corr <-cor(cell2location_abundances)
  p.mat <- cor.mtest(cell2location_abundances)
  print(obj) 
  rm(obj)
  pdf(paste0(save_path, "thresholded_correlation_",group,".pdf"), height = 10, width=15)
  corrplot(cell2location_abundances_corr, type = "upper", 
           p.mat = p.mat, sig.level = 0.05, insig = "blank", tl.col="black", tl.srt=45,
           order="hclust")
    corrplot(cell2location_abundances_corr, type = "lower", 
           p.mat = p.mat, sig.level = 0.05, insig = "blank", tl.col="black", tl.srt=45,
           order="hclust")
  
  corrplot(cell2location_abundances_corr, type="upper", 
           p.mat = p.mat, sig.level = 0.01, insig = "blank", tl.col="black", tl.srt=45,
           col=brewer.pal(n=8, name="PuOr"))
  
  corrplot(cell2location_abundances_corr, type="upper", 
           p.mat = p.mat, sig.level = 0.001, insig = "blank", tl.col="black", tl.srt=45,
           col=brewer.pal(n=8, name="PuOr"))
  dev.off() 
}
only_mm2108_skin_merged<-SetIdent(only_mm2108_skin_merged, value = "seurat_clusters") 
```

##################################
-PDFs containing:
Main figure 8b & e
##################################

```{r}
#groups<-c("untreated","UVB-treated","untreated_Infd16","uvb_treated_Infd16")
counter<-1
only_mm2108_skin_merged<-SetIdent(only_mm2108_skin_merged, value = "group")
#only_mm2108_skin_merged.small <- subset(only_mm2108_skin_merged, downsample = 200)
list_graph<-list()
#https://www.biostars.org/p/285296/
#https://kateto.net/networks-r-igraph

for(group in unique(only_mm2108_skin_merged$group)){
  obj<-subset(only_mm2108_skin_merged, idents=group)
  cell2location_abundances<-obj@meta.data[, thresh_cell_types]
  #cell2location_abundances_corr <-cor(cell2location_abundances)
  #create distance metric
  df<-1-cor(cell2location_abundances, method="pearson")
  #run hclust
  #find_cell_niches(t(cell2location_abundances))
  # Create a graph adjacency based on correlation distances between cell types in  pairwise fashion.
  g <- graph.adjacency(df, mode="undirected", weighted=TRUE, diag=FALSE)
  
  # Simplfy the adjacency object
  g <- simplify(g, remove.multiple=TRUE, remove.loops=TRUE)
  
  
  # Colour negative correlation edges as blue
  E(g)[which(E(g)$weight>1)]$color <- "darkred"

  # Colour positive correlation edges as red
  E(g)[which(E(g)$weight<1)]$color <- "darkblue"

  # Convert edge weights to absolute values
  #E(g)$weight <- abs(E(g)$weight)

  # Change arrow size
  # For directed graphs only
  #E(g)$arrow.size <- 1.0
  
  # Remove edges below absolute Pearson correlation (0.2 or 1-0.2)
  g <- delete_edges(g, E(g)[which(E(g)$weight>0.8)])
  
  # Remove any vertices remaining that have no edges
  g <- delete_vertices(g, igraph::degree(g)==0)
  
  # Assign names to the graph vertices (optional)
  #V(g)$name <- V(g)$name
  V(g)$name <- colnames(cell2location_abundances)
  # Change shape of graph vertices
  V(g)$shape <- "sphere"
  # Change colour of graph vertices
  V(g)$color <- "lightblue"
  # Change colour of vertex frames
  V(g)$vertex.frame.color <- "white"
  
  V(g)
  E(g)
  
  # Scale the size of the vertices to be proportional to the level of expression of   each cell type represented by each vertex
  # Multiply scaled vales by a factor of 10
  scale01 <- function(x){(x-min(x))/(max(x)-min(x))}
  ###########################################################################
  vSizes <- (scale01(apply(t(cell2location_abundances), 1, mean)) + 1.0) * 10

  # Amplify or decrease the width of the edges
  edgeweights <- E(g)$weight * 2.0
  
  # Convert the graph adjacency object into a minimum spanning tree based on Prim's algorithm
  mst <- mst(g, algorithm="prim")
  #find communities
  mst.communities <- cluster_louvain(mst)
  #plot the graph
  mst.clustering <- make_clusters(mst, membership=mst.communities$membership)
  V(mst)$color <- mst.communities$membership + 1
  
  
  pdf(file = paste0(save_path, group, "_thresholded_fig8_igraph.pdf"))
  plot(
    mst.clustering, mst,
    layout=layout.fruchterman.reingold,
    edge.curved=TRUE,
    vertex.size=vSizes,
    vertex.label.dist=-0.3,
    vertex.label.color="black",
    asp=FALSE,
    vertex.label.cex=1,
    edge.width=edgeweights,
    edge.arrow.mode=0,
    main=paste0("Clusters_",group)
    )
  dev.off()
  list_graph[[group]]<-mst.clustering
  counter<-counter+1
}

```
